### ISSUE TITLE
There are some issues with remove the people from this image.

### ISSUE THREAD

**Issue by tianyang1027** [microsoft/TaskMatrix#234]
![image](https://user-images.githubusercontent.com/7963894/225825852-ea90171e-0465-4417-b331-7d65a8b7c82d.png)
![image](https://user-images.githubusercontent.com/7963894/225825918-431dfcf2-0ded-4be6-99e5-e835b36f953e.png)

**Comment by Wang-Xiaodong1899** [comment]
Hi @tianyang1027, can you provide this image? So I can reproduce this problem.

**Comment by tianyang1027** [comment]
image link: https://d2studios.net/wp-content/uploads/blog/2016/01/professional-portrait.jpg

**Comment by Wang-Xiaodong1899** [comment]
Hi @tianyang1027 , this is a good result use the man.
![image](https://user-images.githubusercontent.com/44627574/225847248-8bed31ee-c67d-4949-be30-a675c80e6145.png)
But I find it will go wrong if I use the word "people" for this image, because the MaskFormer (actually the VFM we used) cannot find the "people" in this image.

BTW, have you load the `ImageEditing`? The parameter `--load` you used should include `ImageEditing`, so it can successfully trigger the ImageEditing if you refer the word such as "remove".

**Comment by Wang-Xiaodong1899** [comment]
Not correct. You should use the command: `python visual_chatgpt.py --load ImageCaptioning_cpu,ImageEditing_cpu,Text2Image_cpu`. Try it again. Thanks~
